---
- name: Install NGINX
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Backup existing index.html file
  ansible.builtin.copy:
    src: /usr/share/nginx/html/index.html
    dest: /tmp/index.html.orig
    remote_src: true

- name: Copy index.html to Nginx directory
  ansible.builtin.copy:
    src: files/index.html
    dest: /usr/share/nginx/html/index.html

- name: Ensure nginx is runnning
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
