---
- name: Install NGINX
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Backup existing index.html file
  copy:
    src: /usr/share/nginx/html/index.html
    dest: /tmp/index.html.orig
    remote_src: true
  
- name: Copy index.html to Nginx directory
  copy:
    src: files/index.html
    dest: /var/www/html/index.html

- name: Ensure nginx is runnning
  systemd:
    name: nginx
    state: started
    enabled: yes
