---
- name: Building AWS EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Update AWS security groups
      amazon.aws.ec2_security_group:
        name: arista_devices
        description: Security Group for Arista Network Devices
        vpc_id: vpc-0e7b4669a95b3ddd2
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            group_id: sg-0bcb42e25b9ea5717
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: "0.0.0.0/0"
          - proto: udp
            from_port: 10051
            to_port: 10051
            group_id: sg-006fa88ffd685f66e
