---
- name: Create ServiceNow Incident
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://3.92.50.168
