---
- name: Check Status of Order Processing System
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Poll order system
    ansible.builtin.uri:
      url: http://34.226.152.156:8080/confirmation.html
