---
- name: Implement ServiceNow Change Request
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Query Change Requests
    servicenow.itsm.change_request_info:
      instance: 
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
      query:
        - short_description: LIKE Install Arista Cloud Router
    register: results

  - name: Print out Incident info 
    debug:
      var: results

  - name: Update Successul Change to Review
    servicenow.itsm.change_request:
      instance: 
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
      state: assess
      number: "{{ results.records[0].number }}"
      assignment_group: Network
      
        