---
- name: Create ServiceNow Incident
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create Order System Incident
      servicenow.itsm.incident_info:
        instance:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        query:
          - short_description: LIKE Order System Down Demo
      register: results

    - name: Print out Incident info
      ansible.builtin.debug:
        var: results

    - name: Close Incident
      servicenow.itsm.incident:
        instance:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        state: closed
        number: "{{ results.records[0].number }}"
        close_code: Solved (Permanently)
        close_notes: Closed
