---
- name: Close ServiceNow Incident
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Query Open Incidents
    servicenow.itsm.incident_info:
#      instance: 
#        host: "{{ host }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
      query:
        - short_description: LIKE Required RHEL Packages Not Installed
    register: results

  - name: Print out Incident info 
    debug:
      var: results

  - name: Close Incident
    servicenow.itsm.incident:
#      instance: 
#        host: "{{ host }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
      state: closed
      number: "{{ results.records[0].number }}"
      close_code: "Solved (Permanently)"
      description: Installed required packages
      close_notes: "Closed"
