---
- name: Create AWS Instance from XML file
  hosts: localhost

  tasks:
    - name: Creating blank variable document
      ansible.builtin.copy:
        src: /var/lib/awx/projects/playbooks/bae_new.yml
        dest: /var/lib/awx/projects/playbooks/bae.yml
        mode: "0644"

    - name: Convert XML Instance Name
      register: name
      community.general.xml:
        path: /var/lib/awx/projects/playbooks/emof_v2.xml
        xpath: /Instance/name
        content: text

    - name: Show attribute value
      ansible.builtin.debug:
        var: name.matches

    - name: Write to vars file
      ansible.builtin.lineinfile:
        path: /var/lib/awx/projects/playbooks/bae.yml
        line: "{{ name.matches }}"
        insertafter: EOF

    - name: Convert XML Instance Type
      register: instance_type
      community.general.xml:
        path: /var/lib/awx/projects/playbooks/emof_v2.xml
        xpath: /Instance/instance_type
        content: text

    - name: Show attribute value
      ansible.builtin.debug:
        var: instance_type.matches

    - name: Write to vars file
      ansible.builtin.lineinfile:
        path: /var/lib/awx/projects/playbooks/bae.yml
        line: "{{ instance_type.matches }}"
        insertafter: EOF

    - name: Convert XML Image_id
      register: image_id
      community.general.xml:
        path: /var/lib/awx/projects/playbooks/emof_v2.xml
        xpath: /Instance/image_id
        content: text

    - name: Show attribute value
      ansible.builtin.debug:
        var: image_id.matches

    - name: Write to vars file
      ansible.builtin.lineinfile:
        path: /var/lib/awx/projects/playbooks/bae.yml
        line: "{{ image_id.matches }}"
        insertafter: EOF

    - name: Convert XML Number of Instances
      register: num_instances
      community.general.xml:
        path: /var/lib/awx/projects/playbooks/emof_v2.xml
        xpath: /Instance/num_instances
        content: text

    - name: Show attribute value
      ansible.builtin.debug:
        var: num_instances.matches

    - name: Write to vars file
      ansible.builtin.lineinfile:
        path: /var/lib/awx/projects/playbooks/bae.yml
        line: "{{ num_instances.matches }}"
        insertafter: EOF

    - name: Convert XML Public IP
      register: assign_public_ip
      community.general.xml:
        path: /var/lib/awx/projects/playbooks/emof_v2.xml
        xpath: /Instance/assign_public_ip
        content: text

    - name: Show attribute value
      ansible.builtin.debug:
        var: assign_public_ip.matches

    - name: Write to vars file
      ansible.builtin.lineinfile:
        path: /var/lib/awx/projects/playbooks/bae.yml
        line: "{{ assign_public_ip.matches }}"
        insertafter: EOF

    - name: Convert XML Region
      register: region
      community.general.xml:
        path: /var/lib/awx/projects/playbooks/emof_v2.xml
        xpath: /Instance/region
        content: text

    - name: Show attribute value
      ansible.builtin.debug:
        var: region.matches

    - name: Write to vars file
      ansible.builtin.lineinfile:
        path: /var/lib/awx/projects/playbooks/bae.yml
        line: "{{ region.matches }}"
        insertafter: EOF

    - name: Convert XML Volume Name
      register: device_name
      community.general.xml:
        path: /var/lib/awx/projects/playbooks/emof_v2.xml
        xpath: /Instance/device_name
        content: text

    - name: Show attribute value
      ansible.builtin.debug:
        var: device_name.matches

    - name: Write to vars file
      ansible.builtin.lineinfile:
        path: /var/lib/awx/projects/playbooks/bae.yml
        line: "{{ device_name.matches }}"
        insertafter: EOF

    - name: Convert XML Volume Size
      register: volume_size
      community.general.xml:
        path: /var/lib/awx/projects/playbooks/emof_v2.xml
        xpath: /Instance/volume_size
        content: text

    - name: Show attribute value
      ansible.builtin.debug:
        var: volume_size.matches

    - name: Write to vars file
      ansible.builtin.lineinfile:
        path: /var/lib/awx/projects/playbooks/bae.yml
        line: "{{ volume_size.matches }}"
        insertafter: EOF

    - name: Creating variables file
      ansible.builtin.command:
        cmd: /var/lib/awx/projects/playbooks/convert.sh
