---
- name: Create ServiceNow Incident
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Create Incident - Packages not installed
    servicenow.itsm.incident:
      instance: 
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
      caller: troy.ellis
      short_description: Required RHEL Packages Not Installed
      description: Apache, mariadb, mod_ssl not installed on RHEL Servers
      impact: high
      urgency: high
      state: in_progress
