---
- name: Building AWS EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - /var/lib/awx/projects/playbooks/bae.yml
 
  tasks:
  - name: Create EC2 instance
    amazon.aws.ec2_instance:
      name: "{{ name }}"
      instance_type: "{{ instance_type }}" 
      image_id: "{{ image_id  }}"
      count: "{{ num_instances }}"
      key_name: trellis_aap2
      network:
        assign_public_ip: "{{ assign_public_ip  }}"
        subnet_id: subnet-0323549ff78f73ee0
      vpc_subnet_id: subnet-0323549ff78f73ee0
      security_group: sg-038af1904983955b1
      wait: yes
      region: "{{ region }}"
      volumes:
        - device_name: "{{ device_name }}"
          ebs:
            volume_size: "{{ volume_size }}"
            delete_on_termination: true
