---
- name: Create ServiceNow Change Request
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Create Change Request Provision VMWare VMs
    servicenow.itsm.change_request:
#      instance: 
#        host: "{{ host }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
      type: standard
      state: new
      short_description: Provision new RHEL VM
      description: Provision VM in VMWare 
      priority: moderate
      category: network
      risk: low
      impact: low
      assignment_group: Network
