---
- name: Taking Backup of device
  hosts: edge
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Taking snapshot prior to updating
    amazon.aws.ec2_snapshot:
      instance_id: "{{ instance_id }}"
      device_name: "{{ device_name }}"
      description: snapshot before software update
      snapshot_tags:
        source: /data
        name: edge_node_1