---
- name: Taking Backup of device
  hosts: edge
  gather_facts: false

  tasks:
  - name: Taking snapshot prior to updating
    amazon.aws.ec2_snapshot:
      instance_id: "{{ instance_id }}"
      volume_id: "{{ volume_id }}"
      description: snapshot before software update
      snapshot_tags:
        source: /data
        name: edge_node_1