---
- name: Building EE
  hosts: ee_build_server
  gather_facts: false

  tasks:
  - name: Check if destination directory exists
    ansible.builtin.stat:
      path: /home/ec2-user/ee_builds
    register: dest_dir

  - name: Git clone repo 
    ansible.builtin.command:
      cmd: git clone https://github.com/tellis4151/ee_builds.git /home/ec2-user
    when: not dest_dir.stat.exists
    
  - name: Podman login
    ansible.builtin.command:
      cmd: podman login  --username "{{ username }}" --password "{{ password }}"

  - name: Run Ansible builder create command 
    ansible.builtin.command:
      cmd: ansible-builder create -v 3
      args:
        chdir: /home/ec2-user/ee_builds

  - name: Run Ansible builder build command
    ansible.builtin.command:
      cmd: ansible-builder build -f execution-environment.yml -v 3 -t localhost/iac_ee_new:latest
      args:
        chdir: /home/ec2-user/ee_builds

  - name: Run podman images
    ansible.builtin.command:
      cmd: podman images
    register: ee_images

  - name: Print EE images
    debug:
      var: ee_images 
  