---
- name: Setup Mysql
  hosts: db_servers
  become: True
  vars:
    ansible_python_intrepreter: /usr/bin/python3

  tasks:
  - name: Install mysql on database servers
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: Start and enable on boot
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true
  
  - name: Create lightspeed database
    community.mysql.mysql_db:
      name: lightspeed
      state: present
  

  
    
  
  
  