---
- name: Update security patches on RHEL servers
  hosts: rhel_servers
  gather_facts: false
  become: true

  tasks:
    - name: Register system
      community.general.redhat_subscription:
        state: present
        username: "{{ username }}"
        password: "{{ password }}"
        auto_attach: true
      register: registration_output

    - name: Update security packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        security: true
