---
- name: Start EC2 Instance
  tags: start_ec2
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Start EC2 Instance
    amazon.aws.ec2_instance:
      region: us-east-1
      instance_ids: "{{ instance_ids }}"
      state: started
      wait: false
    
