---
- name: Updating Software Package
  hosts: edge
  tags: update
  gather_facts: false
  become: true

  tasks:
  - name: Update Software
    dnf: 
      name:
        - httpd
        - git
        - mysql
      state: latest

  
