---
- name: Update Task in CR
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Update Server Provisioning Change Request
    servicenow.itsm.change_request_info:
      instance: 
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
      query:
        - short_description: LIKE Provision New RHEL Server
    register: results

  - name: Print out Change Request
    debug:
      var: results

  - name: Update task
    servicenow.itsm.change_request_task:
      change_request_number: "{{ results.records[0].number }}"
      type: implementation
      state: pending
      assigned_to: Troy Ellis
      assignment_group: Network
      short_description: Provision New RHEL Server
      description: "Provision Server Workflow"
      on_hold: true
      hold_reason: "Configuration applied by Ansible had an error"
