---
- name: Updating Software Packages
  hosts: servers
  gather_facts: false
  become: true

  tasks:
    - name: Install Packages
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
          - mariadb
        state: present
