---
- name: Update Task in CR
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Create Order System Incident
    servicenow.itsm.change_request_info:
#      instance: 
#        host: "{{ host }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
      query:
        - short_description: LIKE Configure new servers
    register: results

  - name: Print out Incident info 
    debug:
      var: results

  - name: Update task
    servicenow.itsm.change_request_task:
#      change_request_number: "{{ results.records[0].number }}"
      change_request_number: "{{ change_number }}"
      type: implementation
      state: pending
      assigned_to: Troy Ellis
      assignment_group: Network
      short_description: Configure new servers
      description: "Install Security Patches, Register System, Install applicaton sofware, Enable FIPS"
      on_hold: true
      hold_reason: "Configuration applied by Ansible had an error"
