---
- name: Updating Software Package
  hosts: edge
  tags: update
  gather_facts: false
  become: true

  tasks:
    - name: Update Software
      ansible.builtin.dnf:
        name:
          - net-tools
          - sysstat
          - git
        state: latest
