---
- name: Updating Software Package
  hosts: edge
  tags: update
  gather_facts: false
  become: true

  tasks:
    - name: Update Software
      ansible.builtin.dnf:
        name:
          - httpd
          - git
        state: latest
