---
- name: Updating Software Package
  hosts: edge
  tags: update
  gather_facts: false
  become: true

  tasks:
    - name: Update Software
      ansible.builtin.shell:
        cmd: /home/rocky/firmware.sh
