---
- name: Update Task in CR
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create Order System Incident
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        query:
          - short_description: LIKE Install Arista Cloud Router
      register: results

    - name: Print out Incident info
      ansible.builtin.debug:
        var: results

    - name: Update task
      servicenow.itsm.change_request_task:
        change_request_number: "{{ results.records[0].number }}"
        type: implementation
        state: pending
        assigned_to: Troy Ellis
        assignment_group: Network
        short_description: Applying Arista Configurations
        description: Provisioning Arista Cloud Router
        on_hold: true
        hold_reason: Configuration applied by Ansible had an error
