---
- name: Remove IIS Advanced Configurations
  hosts: windows
  vars:
    iis_sites:
      - name: 'Ansible Playbook Test'
        port: '8080'
        path: 'C:\sites\playbooktest'
      - name: 'Ansible Playbook Test 2'
        port: '8081'
        path: 'C:\sites\playbooktest2'

  tasks:
    - name: Stop iis service
      ansible.windows.win_service:
        name: W3Svc
        state: stopped

    - name: Remove site directory structure
      ansible.windows.win_file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ iis_sites }}"

    - name: Remove IIS site
      community.windows.win_iis_website:
        name: "{{ item.name }}"
        state: absent
        port: "{{ item.port }}"
        physical_path: "{{ item.path }}"
      with_items: "{{ iis_sites }}"

    - name: Remove IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: absent

    - name: Remove port for site on the firewall
      community.windows.win_firewall_rule:
        name: "iisport{{ item.port }}"
        state: absent
        localport: "{{ item.port }}"
        action: Allow
        direction: In
        protocol: Tcp
      with_items: "{{ iis_sites }}"